"""
Django settings for gastronomia project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import pymysql
pymysql.install_as_MySQLdb()

import os
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables desde Back-end/gastronomia/.env si python-dotenv está instalado
# (pip install python-dotenv). Si no, se usan las variables de entorno del sistema.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _leer_env(nombre, por_defecto=None):
    valor = os.environ.get(nombre, por_defecto)
    if valor is None:
        raise ImproperlyConfigured(
            f"Falta la variable de entorno {nombre}. Copia .env.example a .env y complétala."
        )
    return valor


def _leer_lista(nombre, por_defecto=''):
    return [v.strip() for v in os.environ.get(nombre, por_defecto).split(',') if v.strip()]


def _leer_primero(nombres, por_defecto=''):
    """Devuelve la primera variable definida de la lista (ej. DB_HOST o, en Railway, MYSQLHOST)."""
    for nombre in nombres:
        if os.environ.get(nombre):
            return os.environ[nombre]
    return por_defecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _leer_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _leer_env('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = _leer_lista('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Railway expone el dominio público del servicio en esta variable.
_DOMINIO_RAILWAY = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if _DOMINIO_RAILWAY:
    ALLOWED_HOSTS.append(_DOMINIO_RAILWAY)

# Las cookies solo viajan por HTTPS cuando DEBUG está apagado (producción).
AUTH_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

if not DEBUG:
    # Railway termina el HTTPS en su proxy y reenvía la petición por HTTP.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

import cloudinary

# Application definition

INSTALLED_APPS = [
    'cloudinary',
    #'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'rest_framework',
    'rest_framework_simplejwt',
]


cloudinary.config(
    cloud_name = _leer_env('CLOUDINARY_CLOUD_NAME', ''),
    api_key = _leer_env('CLOUDINARY_API_KEY', ''),
    api_secret = _leer_env('CLOUDINARY_API_SECRET', ''),
    secure=True
)

#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'api.PerfilUsuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sirve los estáticos (admin, DRF) en producción
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Orígenes del front-end. En producción, con el proxy /api de Vercel, el navegador habla con un
# solo dominio y CORS casi no interviene; aun así se puede ampliar con CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
] + _leer_lista('CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Deben incluir el esquema (https://...). Se usa, por ejemplo, para entrar al /admin de Django.
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"] + _leer_lista('CSRF_TRUSTED_ORIGINS')
if _DOMINIO_RAILWAY:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_DOMINIO_RAILWAY}")

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
  
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.middleware.CookieJWTAuthentication',
    ],

    # Cerrado por defecto: cada vista pública debe declararlo explícitamente
    # (ver api/permissions.py).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     
    'ROTATE_REFRESH_TOKENS': True,                  
    'BLACKLIST_AFTER_ROTATION': True,               
    'UPDATE_LAST_LOGIN': True,                      
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),              
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

ROOT_URLCONF = 'gastronomia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gastronomia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # con PyMySQL (ver pymysql.install_as_MySQLdb arriba)
        # Railway define MYSQLDATABASE, MYSQLUSER, ...; DB_* tiene prioridad si existen.
        'NAME': _leer_primero(['DB_NAME', 'MYSQLDATABASE'], 'gastronomia'),
        'USER': _leer_primero(['DB_USER', 'MYSQLUSER'], 'root'),
        'PASSWORD': _leer_primero(['DB_PASSWORD', 'MYSQLPASSWORD'], ''),
        'HOST': _leer_primero(['DB_HOST', 'MYSQLHOST'], '127.0.0.1'),
        'PORT': int(_leer_primero(['DB_PORT', 'MYSQLPORT'], '3306')),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = True